-- Sonnet 4.6 "sınırsız" günlük paket kartları.
--
-- Not:
-- - Bedrock/provider adı müşteri görünen ad/açıklamada geçmez.
-- - Gerçek routing model/lane üzerinden yapılır: claude-sonnet-4-6 -> bedrock-sonnet-global.
-- - Şema gerçek sonsuz kota desteklemediği için "sınırsız" günlük paket sentinel
--   limit kullanır. Sistemsel Bedrock lane RPM sınırı yine ayrıca çalışır.
-- - satista=false: kart görünür, satın alma kapalı. Fiyat/satış admin panelden açılabilir.

INSERT INTO packages (
  id,
  ad,
  kategori,
  aciklama,
  tip,
  gunluk_istek_limiti,
  sure_gun,
  allowed_models,
  fiyat_tl,
  fiyat_usd,
  enabled,
  display_order,
  satista,
  max_context_tokens,
  tpm_limit,
  birim_tipi,
  devreden,
  saatlik_limit,
  sure_saat,
  provider_model_map,
  is_token_pool,
  premium_model_id,
  updated_at
) VALUES
  (
    'sonnet-unlimited-1d',
    'Sonnet 4.6 Sınırsız — 1 Gün',
    'Claude',
    'Sonnet 4.6 erişimi. 24 saat geçerli. Günlük kota sınırsız olarak tanımlıdır; yoğunluk durumunda adil kullanım hız kuyruğu uygulanır.',
    'request_limit',
    1000000,
    1,
    '["claude-sonnet-4-6"]'::jsonb,
    0,
    0,
    true,
    3,
    false,
    1000000,
    null,
    'istek',
    false,
    null,
    24,
    '{}'::jsonb,
    false,
    'claude-sonnet-4-6',
    now()
  ),
  (
    'sonnet-unlimited-3d',
    'Sonnet 4.6 Sınırsız — 3 Gün',
    'Claude',
    'Sonnet 4.6 erişimi. 3 gün geçerli. Günlük kota sınırsız olarak tanımlıdır; yoğunluk durumunda adil kullanım hız kuyruğu uygulanır.',
    'request_limit',
    1000000,
    3,
    '["claude-sonnet-4-6"]'::jsonb,
    0,
    0,
    true,
    4,
    false,
    1000000,
    null,
    'istek',
    false,
    null,
    72,
    '{}'::jsonb,
    false,
    'claude-sonnet-4-6',
    now()
  ),
  (
    'sonnet-unlimited-7d',
    'Sonnet 4.6 Sınırsız — 7 Gün',
    'Claude',
    'Sonnet 4.6 erişimi. 7 gün geçerli. Günlük kota sınırsız olarak tanımlıdır; yoğunluk durumunda adil kullanım hız kuyruğu uygulanır.',
    'request_limit',
    1000000,
    7,
    '["claude-sonnet-4-6"]'::jsonb,
    0,
    0,
    true,
    5,
    false,
    1000000,
    null,
    'istek',
    false,
    null,
    168,
    '{}'::jsonb,
    false,
    'claude-sonnet-4-6',
    now()
  )
ON CONFLICT (id) DO UPDATE SET
  ad = EXCLUDED.ad,
  kategori = EXCLUDED.kategori,
  aciklama = EXCLUDED.aciklama,
  tip = EXCLUDED.tip,
  gunluk_istek_limiti = EXCLUDED.gunluk_istek_limiti,
  sure_gun = EXCLUDED.sure_gun,
  allowed_models = EXCLUDED.allowed_models,
  fiyat_tl = EXCLUDED.fiyat_tl,
  fiyat_usd = EXCLUDED.fiyat_usd,
  enabled = EXCLUDED.enabled,
  display_order = EXCLUDED.display_order,
  satista = EXCLUDED.satista,
  max_context_tokens = EXCLUDED.max_context_tokens,
  tpm_limit = EXCLUDED.tpm_limit,
  birim_tipi = EXCLUDED.birim_tipi,
  devreden = EXCLUDED.devreden,
  saatlik_limit = EXCLUDED.saatlik_limit,
  sure_saat = EXCLUDED.sure_saat,
  provider_model_map = EXCLUDED.provider_model_map,
  is_token_pool = EXCLUDED.is_token_pool,
  premium_model_id = EXCLUDED.premium_model_id,
  updated_at = now();
