export type ModelModality = "audio" | "image" | "text" | "video";

export interface MasterModelEndpoint {
  type: string;
  supportsStreaming: boolean;
  supportedParameters: string[];
}

export interface MasterModel {
  id: string;
  name: string;
  provider: string;
  providerSlug?: string;
  type: "Metin" | "Görsel" | "Video";
  context: string;
  contextTokens?: number | null;
  maxOutputTokens?: number | null;
  description?: string | null;
  aliases?: string[];
  inputModalities?: ModelModality[];
  outputModalities?: ModelModality[];
  endpoints: string[];
  endpointDetails?: MasterModelEndpoint[];
  supportedParameters?: string[];
  pricingUnit?: "usd_per_million_tokens" | "usd_per_second";
  providerInputUsd?: number;
  providerOutputUsd?: number;
  providerImageInputUsd?: number;
  providerImageOutputUsd?: number;
  providerPerSecond?: {
    default?: number;
    "480p"?: number;
    "720p"?: number;
    "1080p"?: number;
  };
}

export const MASTER_MODELS: MasterModel[] = [
  // Anthropic
  {
    id: "anthropic/claude-haiku-4.5",
    name: "Claude Haiku 4.5",
    provider: "Anthropic",
    providerSlug: "anthropic",
    type: "Metin",
    context: "200K",
    contextTokens: 200000,
    maxOutputTokens: 64000,
    description: null,
    aliases: ["anthropic/claude-haiku-4-5","anthropic/claude-haiku-4-5-20251001","anthropic/claude-haiku-4-5.20251001","anthropic/claude-haiku-4.5-20251001","anthropic/cursor-claude-haiku-4.5"],
    inputModalities: ["image","text"],
    outputModalities: ["text"],
    endpoints: ["chat","messages"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["container","max_tokens","messages","metadata","model","output_config","service_tier","stop_sequences","stream","system","temperature","thinking","tool_choice","tools","top_k","top_p"]},{"type":"messages","supportsStreaming":true,"supportedParameters":["container","max_tokens","messages","metadata","model","output_config","service_tier","stop_sequences","stream","system","temperature","thinking","tool_choice","tools","top_k","top_p"]}],
    supportedParameters: ["container","max_tokens","messages","metadata","model","output_config","service_tier","stop_sequences","stream","system","temperature","thinking","tool_choice","tools","top_k","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.15,
    providerOutputUsd: 0.15,
  },
  {
    id: "anthropic/claude-opus-4.6",
    name: "Claude Opus 4.6",
    provider: "Anthropic",
    providerSlug: "anthropic",
    type: "Metin",
    context: "1M",
    contextTokens: 1000000,
    maxOutputTokens: 128000,
    description: null,
    aliases: ["anthropic/claude-opus-4-6","anthropic/cursor-claude-opus-4.6"],
    inputModalities: ["image","text"],
    outputModalities: ["text"],
    endpoints: ["chat","messages"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["include_reasoning","max_completion_tokens","max_tokens","reasoning","response_format","stop","structured_outputs","temperature","tool_choice","tools","top_k","top_p","verbosity"]},{"type":"messages","supportsStreaming":true,"supportedParameters":["include_reasoning","max_completion_tokens","max_tokens","reasoning","response_format","stop","structured_outputs","temperature","tool_choice","tools","top_k","top_p","verbosity"]}],
    supportedParameters: ["include_reasoning","max_completion_tokens","max_tokens","reasoning","response_format","stop","structured_outputs","temperature","tool_choice","tools","top_k","top_p","verbosity"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.3,
    providerOutputUsd: 0.3,
  },
  {
    id: "anthropic/claude-opus-4.7",
    name: "Claude Opus 4.7",
    provider: "Anthropic",
    providerSlug: "anthropic",
    type: "Metin",
    context: "1M",
    contextTokens: 1000000,
    maxOutputTokens: 128000,
    description: null,
    aliases: ["anthropic/claude-opus-4-7","anthropic/cursor-claude-opus-4.7"],
    inputModalities: ["image","text"],
    outputModalities: ["text"],
    endpoints: ["chat","messages"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["container","max_tokens","messages","metadata","model","output_config","service_tier","stop_sequences","stream","system","temperature","thinking","tool_choice","tools","top_k","top_p"]},{"type":"messages","supportsStreaming":true,"supportedParameters":["container","max_tokens","messages","metadata","model","output_config","service_tier","stop_sequences","stream","system","temperature","thinking","tool_choice","tools","top_k","top_p"]}],
    supportedParameters: ["container","max_tokens","messages","metadata","model","output_config","service_tier","stop_sequences","stream","system","temperature","thinking","tool_choice","tools","top_k","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.3,
    providerOutputUsd: 0.3,
  },
  {
    id: "anthropic/claude-sonnet-4.6",
    name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    providerSlug: "anthropic",
    type: "Metin",
    context: "1M",
    contextTokens: 1000000,
    maxOutputTokens: 128000,
    description: null,
    aliases: ["anthropic/claude-sonnet-4-6","anthropic/cursor-claude-sonnet-4.6"],
    inputModalities: ["image","text"],
    outputModalities: ["text"],
    endpoints: ["chat","messages"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["container","max_tokens","messages","metadata","model","output_config","service_tier","stop_sequences","stream","system","temperature","thinking","tool_choice","tools","top_k","top_p"]},{"type":"messages","supportsStreaming":true,"supportedParameters":["container","max_tokens","messages","metadata","model","output_config","service_tier","stop_sequences","stream","system","temperature","thinking","tool_choice","tools","top_k","top_p"]}],
    supportedParameters: ["container","max_tokens","messages","metadata","model","output_config","service_tier","stop_sequences","stream","system","temperature","thinking","tool_choice","tools","top_k","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.255,
    providerOutputUsd: 0.255,
  },
  // ByteDance
  {
    id: "bytedance/seedance-2.0",
    name: "Seedance 2.0",
    provider: "ByteDance",
    providerSlug: "bytedance",
    type: "Video",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["audio","image","text","video"],
    outputModalities: ["video"],
    endpoints: ["chat","videos_submit","videos_task"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","callback_url","duration","enable_web_search","generate_audio","negative_prompt","prompt","reference_audios","reference_images","reference_videos","resolution","seed","size"]},{"type":"videos_submit","supportsStreaming":true,"supportedParameters":["aspect_ratio","callback_url","duration","enable_web_search","generate_audio","negative_prompt","prompt","reference_audios","reference_images","reference_videos","resolution","seed","size"]},{"type":"videos_task","supportsStreaming":true,"supportedParameters":[]}],
    supportedParameters: ["aspect_ratio","callback_url","duration","enable_web_search","generate_audio","negative_prompt","output_config","prompt","reference_audios","reference_images","reference_videos","resolution","seed","size"],
    pricingUnit: "usd_per_second",
    providerPerSecond: {"480p":0.016815,"720p":0.0378,"1080p":0.08505},
  },
  {
    id: "bytedance/seedance-2.0-edit",
    name: "Seedance 2.0 Edit",
    provider: "ByteDance",
    providerSlug: "bytedance",
    type: "Video",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["audio","image","text","video"],
    outputModalities: ["video"],
    endpoints: ["chat","videos_submit","videos_task"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","callback_url","duration","enable_web_search","generate_audio","prompt","reference_audios","reference_images","resolution","video"]},{"type":"videos_submit","supportsStreaming":true,"supportedParameters":["aspect_ratio","callback_url","duration","enable_web_search","generate_audio","prompt","reference_audios","reference_images","resolution","video"]},{"type":"videos_task","supportsStreaming":true,"supportedParameters":[]}],
    supportedParameters: ["aspect_ratio","callback_url","duration","enable_web_search","generate_audio","output_config","prompt","reference_audios","reference_images","resolution","video"],
    pricingUnit: "usd_per_second",
    providerPerSecond: {"480p":0.016815,"720p":0.0378,"1080p":0.08505},
  },
  {
    id: "bytedance/seedance-2.0-extend",
    name: "Seedance 2.0 Extend",
    provider: "ByteDance",
    providerSlug: "bytedance",
    type: "Video",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["image","text","video"],
    outputModalities: ["video"],
    endpoints: ["chat","videos_submit","videos_task"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["callback_url","duration","enable_web_search","generate_audio","last_image","negative_prompt","prompt","resolution","seed","size","video"]},{"type":"videos_submit","supportsStreaming":true,"supportedParameters":["callback_url","duration","enable_web_search","generate_audio","last_image","negative_prompt","prompt","resolution","seed","size","video"]},{"type":"videos_task","supportsStreaming":true,"supportedParameters":[]}],
    supportedParameters: ["callback_url","duration","enable_web_search","generate_audio","last_image","negative_prompt","output_config","prompt","resolution","seed","size","video"],
    pricingUnit: "usd_per_second",
    providerPerSecond: {"480p":0.016815,"720p":0.0378,"1080p":0.08505},
  },
  {
    id: "bytedance/seedance-2.0-i2v",
    name: "Seedance 2.0 i2v",
    provider: "ByteDance",
    providerSlug: "bytedance",
    type: "Video",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["image","text"],
    outputModalities: ["video"],
    endpoints: ["chat","videos_submit","videos_task"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","callback_url","duration","enable_web_search","frame_images","generate_audio","image","input_references","last_image","negative_prompt","prompt","resolution","seed","size"]},{"type":"videos_submit","supportsStreaming":true,"supportedParameters":["aspect_ratio","callback_url","duration","enable_web_search","frame_images","generate_audio","image","input_references","last_image","negative_prompt","prompt","resolution","seed","size"]},{"type":"videos_task","supportsStreaming":true,"supportedParameters":[]}],
    supportedParameters: ["aspect_ratio","callback_url","duration","enable_web_search","frame_images","generate_audio","image","input_references","last_image","negative_prompt","output_config","prompt","resolution","seed","size"],
    pricingUnit: "usd_per_second",
    providerPerSecond: {"480p":0.016815,"720p":0.0378,"1080p":0.08505},
  },
  // Deepseek
  {
    id: "deepseek/deepseek-v4-pro",
    name: "Deepseek V4 Pro",
    provider: "Deepseek",
    providerSlug: "deepseek",
    type: "Metin",
    context: "1.05M",
    contextTokens: 1048576,
    maxOutputTokens: 384000,
    description: null,
    inputModalities: ["text"],
    outputModalities: ["text"],
    endpoints: ["chat"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["frequency_penalty","include_reasoning","logprobs","max_tokens","presence_penalty","reasoning","response_format","stop","temperature","tool_choice","tools","top_logprobs","top_p"]}],
    supportedParameters: ["frequency_penalty","include_reasoning","logprobs","max_tokens","presence_penalty","reasoning","response_format","stop","temperature","tool_choice","tools","top_logprobs","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.1,
    providerOutputUsd: 0.1,
  },
  // Google
  {
    id: "google/gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    providerSlug: "google",
    type: "Metin",
    context: "1.05M",
    contextTokens: 1048576,
    maxOutputTokens: 65536,
    description: null,
    inputModalities: ["image","text"],
    outputModalities: ["text"],
    endpoints: ["chat"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["include_reasoning","max_tokens","reasoning","response_format","seed","stop","structured_outputs","temperature","tool_choice","tools","top_p"]}],
    supportedParameters: ["include_reasoning","max_tokens","reasoning","response_format","seed","stop","structured_outputs","temperature","tool_choice","tools","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.11,
    providerOutputUsd: 0.11,
  },
  {
    id: "google/gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    provider: "Google",
    providerSlug: "google",
    type: "Metin",
    context: "1.05M",
    contextTokens: 1048576,
    maxOutputTokens: 65536,
    description: null,
    aliases: ["google/gemini-3.1-flash-lite"],
    inputModalities: ["image","text"],
    outputModalities: ["text"],
    endpoints: ["chat"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["include_reasoning","max_tokens","reasoning","response_format","seed","stop","structured_outputs","temperature","tool_choice","tools","top_p"]}],
    supportedParameters: ["include_reasoning","max_tokens","reasoning","response_format","seed","stop","structured_outputs","temperature","tool_choice","tools","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.1,
    providerOutputUsd: 0.1,
  },
  {
    id: "google/gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    provider: "Google",
    providerSlug: "google",
    type: "Metin",
    context: "1.05M",
    contextTokens: 1048576,
    maxOutputTokens: 65536,
    description: null,
    aliases: ["google/gemini-3.1-pro"],
    inputModalities: ["audio","image","text"],
    outputModalities: ["text"],
    endpoints: ["chat"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["include_reasoning","max_tokens","reasoning","response_format","seed","stop","structured_outputs","temperature","tool_choice","tools","top_p"]}],
    supportedParameters: ["include_reasoning","max_tokens","reasoning","response_format","seed","stop","structured_outputs","temperature","tool_choice","tools","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.13,
    providerOutputUsd: 0.13,
  },
  {
    id: "google/nano-banana-2",
    name: "Nano Banana 2",
    provider: "Google",
    providerSlug: "google",
    type: "Görsel",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["text"],
    outputModalities: ["image"],
    endpoints: ["chat","images_generations"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","enable_image_search","enable_web_search","output_format","prompt","resolution"]},{"type":"images_generations","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","enable_image_search","enable_web_search","output_format","prompt","resolution"]}],
    supportedParameters: ["aspect_ratio","enable_base64_output","enable_image_search","enable_web_search","output_format","prompt","resolution"],
    pricingUnit: "usd_per_million_tokens",
    providerImageInputUsd: 0.1,
    providerImageOutputUsd: 0.3,
  },
  {
    id: "google/nano-banana-2-edit",
    name: "Nano Banana 2 Edit",
    provider: "Google",
    providerSlug: "google",
    type: "Görsel",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["image","text"],
    outputModalities: ["image"],
    endpoints: ["chat","images_generations","images_edits"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","images","model","output_format","prompt","resolution","response_format","size"]},{"type":"images_generations","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","images","model","output_format","prompt","resolution","response_format","size"]},{"type":"images_edits","supportsStreaming":false,"supportedParameters":["aspect_ratio","enable_base64_output","images","model","output_format","prompt","resolution","response_format","size"]}],
    supportedParameters: ["aspect_ratio","enable_base64_output","images","model","output_format","prompt","resolution","response_format","size"],
    pricingUnit: "usd_per_million_tokens",
    providerImageInputUsd: 0.1,
    providerImageOutputUsd: 0.3,
  },
  {
    id: "google/nano-banana-pro",
    name: "Nano Banana Pro",
    provider: "Google",
    providerSlug: "google",
    type: "Görsel",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["text"],
    outputModalities: ["image"],
    endpoints: ["chat","images_generations"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","enable_image_search","enable_web_search","output_format","prompt","resolution"]},{"type":"images_generations","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","enable_image_search","enable_web_search","output_format","prompt","resolution"]}],
    supportedParameters: ["aspect_ratio","enable_base64_output","enable_image_search","enable_web_search","output_format","prompt","resolution"],
    pricingUnit: "usd_per_million_tokens",
    providerImageInputUsd: 0.2,
    providerImageOutputUsd: 1.2,
  },
  {
    id: "google/nano-banana-pro-edit",
    name: "Nano Banana Pro Edit",
    provider: "Google",
    providerSlug: "google",
    type: "Görsel",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["image","text"],
    outputModalities: ["image"],
    endpoints: ["chat","images_generations","images_edits"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","images","model","output_format","prompt","resolution","response_format","size"]},{"type":"images_generations","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","images","model","output_format","prompt","resolution","response_format","size"]},{"type":"images_edits","supportsStreaming":false,"supportedParameters":["aspect_ratio","enable_base64_output","images","model","output_format","prompt","resolution","response_format","size"]}],
    supportedParameters: ["aspect_ratio","enable_base64_output","images","model","output_format","prompt","resolution","response_format","size"],
    pricingUnit: "usd_per_million_tokens",
    providerImageInputUsd: 0.2,
    providerImageOutputUsd: 1.2,
  },
  {
    id: "google/veo-3.1",
    name: "Veo 3.1",
    provider: "Google",
    providerSlug: "google",
    type: "Video",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["text"],
    outputModalities: ["video"],
    endpoints: ["chat","videos_submit","videos_task"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","callback_url","duration","generate_audio","negative_prompt","prompt","resolution","seed","size"]},{"type":"videos_submit","supportsStreaming":true,"supportedParameters":["aspect_ratio","duration","generate_audio","negative_prompt","output_config","prompt","resolution","seed"]},{"type":"videos_task","supportsStreaming":true,"supportedParameters":["aspect_ratio","duration","generate_audio","negative_prompt","output_config","prompt","resolution","seed"]}],
    supportedParameters: ["aspect_ratio","callback_url","duration","generate_audio","negative_prompt","output_config","prompt","resolution","seed","size"],
    pricingUnit: "usd_per_second",
    providerPerSecond: {"default":0.03},
  },
  {
    id: "google/veo-3.1-extend",
    name: "Veo 3.1 Extend",
    provider: "Google",
    providerSlug: "google",
    type: "Video",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["text","video"],
    outputModalities: ["video"],
    endpoints: ["chat","videos_submit","videos_task"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["callback_url","negative_prompt","prompt","resolution","seed","size","video"]},{"type":"videos_submit","supportsStreaming":true,"supportedParameters":["negative_prompt","output_config","prompt","resolution","seed","video"]},{"type":"videos_task","supportsStreaming":true,"supportedParameters":["negative_prompt","output_config","prompt","resolution","seed","video"]}],
    supportedParameters: ["callback_url","negative_prompt","output_config","prompt","resolution","seed","size","video"],
    pricingUnit: "usd_per_second",
    providerPerSecond: {"default":0.03},
  },
  {
    id: "google/veo-3.1-i2v",
    name: "Veo 3.1 i2v",
    provider: "Google",
    providerSlug: "google",
    type: "Video",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["image","text"],
    outputModalities: ["video"],
    endpoints: ["chat","videos_submit","videos_task"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","callback_url","duration","frame_images","generate_audio","image","input_references","last_image","negative_prompt","prompt","resolution","seed","size"]},{"type":"videos_submit","supportsStreaming":true,"supportedParameters":["aspect_ratio","duration","generate_audio","image","last_image","negative_prompt","output_config","prompt","resolution","seed"]},{"type":"videos_task","supportsStreaming":true,"supportedParameters":["aspect_ratio","duration","generate_audio","image","last_image","negative_prompt","output_config","prompt","resolution","seed"]}],
    supportedParameters: ["aspect_ratio","callback_url","duration","frame_images","generate_audio","image","input_references","last_image","negative_prompt","output_config","prompt","resolution","seed","size"],
    pricingUnit: "usd_per_second",
    providerPerSecond: {"default":0.03},
  },
  // Kwaivgi
  {
    id: "kwaivgi/kling-v3.0-std",
    name: "Kling v3.0 Standard",
    provider: "Kwaivgi",
    providerSlug: "kwaivgi",
    type: "Video",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["text"],
    outputModalities: ["video"],
    endpoints: ["chat","videos_submit","videos_task"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","cfg_scale","duration","element_list","multi_prompt","negative_prompt","shot_type","sound"]},{"type":"videos_submit","supportsStreaming":true,"supportedParameters":["aspect_ratio","callback_url","cfg_scale","duration","element_list","multi_prompt","negative_prompt","shot_type","sound"]},{"type":"videos_task","supportsStreaming":true,"supportedParameters":[]}],
    supportedParameters: ["aspect_ratio","callback_url","cfg_scale","duration","element_list","multi_prompt","negative_prompt","shot_type","sound"],
    pricingUnit: "usd_per_second",
    providerPerSecond: {"default":0.03},
  },
  {
    id: "kwaivgi/kling-v3.0-std-i2v",
    name: "Kling: 3.0 Standard Image-to-Video",
    provider: "Kwaivgi",
    providerSlug: "kwaivgi",
    type: "Video",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["image","text"],
    outputModalities: ["video"],
    endpoints: ["chat","videos_submit","videos_task"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["cfg_scale","duration","element_list","end_image","frame_images","image","multi_prompt","negative_prompt","shot_type","sound"]},{"type":"videos_submit","supportsStreaming":true,"supportedParameters":["callback_url","cfg_scale","duration","element_list","end_image","frame_images","image","multi_prompt","negative_prompt","shot_type","sound"]},{"type":"videos_task","supportsStreaming":true,"supportedParameters":[]}],
    supportedParameters: ["callback_url","cfg_scale","duration","element_list","end_image","frame_images","image","multi_prompt","negative_prompt","shot_type","sound"],
    pricingUnit: "usd_per_second",
    providerPerSecond: {"default":0.03},
  },
  {
    id: "kwaivgi/kling-v3.0-std-motion-control",
    name: "Kling: 3.0 Standard Motion Control",
    provider: "Kwaivgi",
    providerSlug: "kwaivgi",
    type: "Video",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["image","text","video"],
    outputModalities: ["video"],
    endpoints: ["chat","videos_submit","videos_task"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["character_orientation","element_list","image","keep_original_sound","negative_prompt","shot_type","video"]},{"type":"videos_submit","supportsStreaming":true,"supportedParameters":["callback_url","character_orientation","element_list","image","keep_original_sound","negative_prompt","shot_type","video"]},{"type":"videos_task","supportsStreaming":true,"supportedParameters":[]}],
    supportedParameters: ["callback_url","character_orientation","element_list","image","keep_original_sound","negative_prompt","shot_type","video"],
    pricingUnit: "usd_per_second",
    providerPerSecond: {"default":0.03},
  },
  // MiMo
  {
    id: "mimo/mimo-v2-pro",
    name: "MiMo V2 Pro",
    provider: "MiMo",
    providerSlug: "mimo",
    type: "Metin",
    context: "1.05M",
    contextTokens: 1048576,
    maxOutputTokens: 131072,
    description: null,
    inputModalities: ["text"],
    outputModalities: ["text"],
    endpoints: ["chat"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["frequency_penalty","include_reasoning","max_tokens","presence_penalty","reasoning","response_format","stop","temperature","tool_choice","tools","top_p"]}],
    supportedParameters: ["frequency_penalty","include_reasoning","max_tokens","presence_penalty","reasoning","response_format","stop","temperature","tool_choice","tools","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.1,
    providerOutputUsd: 0.1,
  },
  // MiniMax
  {
    id: "minimax/minimax-m2.7",
    name: "MiniMax M2.7",
    provider: "MiniMax",
    providerSlug: "minimax",
    type: "Metin",
    context: "205K",
    contextTokens: 204800,
    maxOutputTokens: 131072,
    description: null,
    inputModalities: ["text"],
    outputModalities: ["text"],
    endpoints: ["chat"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["frequency_penalty","include_reasoning","logit_bias","logprobs","max_tokens","min_p","presence_penalty","reasoning","repetition_penalty","response_format","stop","structured_outputs","temperature","tool_choice","tools","top_k","top_logprobs","top_p"]}],
    supportedParameters: ["frequency_penalty","include_reasoning","logit_bias","logprobs","max_tokens","min_p","presence_penalty","reasoning","repetition_penalty","response_format","stop","structured_outputs","temperature","tool_choice","tools","top_k","top_logprobs","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.1,
    providerOutputUsd: 0.1,
  },
  // MoonshotAI
  {
    id: "moonshotai/kimi-k2.5",
    name: "Kimi K2.5",
    provider: "MoonshotAI",
    providerSlug: "moonshotai",
    type: "Metin",
    context: "262K",
    contextTokens: 262144,
    maxOutputTokens: 65535,
    description: null,
    inputModalities: ["image","text"],
    outputModalities: ["text"],
    endpoints: ["chat"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["frequency_penalty","include_reasoning","logit_bias","logprobs","max_tokens","min_p","parallel_tool_calls","presence_penalty","reasoning","repetition_penalty","response_format","seed","stop","structured_outputs","temperature","tool_choice","tools","top_k","top_logprobs","top_p"]}],
    supportedParameters: ["frequency_penalty","include_reasoning","logit_bias","logprobs","max_tokens","min_p","parallel_tool_calls","presence_penalty","reasoning","repetition_penalty","response_format","seed","stop","structured_outputs","temperature","tool_choice","tools","top_k","top_logprobs","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.08,
    providerOutputUsd: 0.38,
  },
  // OpenAI
  {
    id: "openai/gpt-5.3-codex",
    name: "GPT 5.3 Codex",
    provider: "OpenAI",
    providerSlug: "openai",
    type: "Metin",
    context: "400K",
    contextTokens: 400000,
    maxOutputTokens: 128000,
    description: null,
    inputModalities: ["image","text"],
    outputModalities: ["text"],
    endpoints: ["chat","responses"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["include_reasoning","max_completion_tokens","max_tokens","reasoning","response_format","seed","structured_outputs","tool_choice","tools"]},{"type":"responses","supportsStreaming":true,"supportedParameters":["include_reasoning","max_completion_tokens","max_tokens","reasoning","response_format","seed","structured_outputs","tool_choice","tools"]}],
    supportedParameters: ["include_reasoning","max_completion_tokens","max_tokens","reasoning","response_format","seed","structured_outputs","tool_choice","tools"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.13,
    providerOutputUsd: 0.13,
  },
  {
    id: "openai/gpt-5.4",
    name: "GPT 5.4",
    provider: "OpenAI",
    providerSlug: "openai",
    type: "Metin",
    context: "1.05M",
    contextTokens: 1050000,
    maxOutputTokens: 128000,
    description: null,
    aliases: ["openai/custom-gpt-5.4-high","openai/custom-gpt-5.4-low","openai/custom-gpt-5.4-medium","openai/custom-gpt-5.4-xhigh"],
    inputModalities: ["image","text"],
    outputModalities: ["text"],
    endpoints: ["chat","responses"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["max_tokens","messages","prompt","reasoning","response_format","seed","stop","temperature","tool_choice","tools","top_p","user"]},{"type":"responses","supportsStreaming":true,"supportedParameters":["instructions","max_output_tokens","reasoning","temperature","text","tool_choice","tools","top_p","user"]}],
    supportedParameters: ["input","instructions","max_output_tokens","max_tokens","messages","metadata","prompt","reasoning","response_format","seed","stop","system","temperature","text","thinking","tool_choice","tools","top_p","user"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.15,
    providerOutputUsd: 0.15,
  },
  {
    id: "openai/gpt-5.4-mini",
    name: "GPT 5.4 Mini",
    provider: "OpenAI",
    providerSlug: "openai",
    type: "Metin",
    context: "400K",
    contextTokens: 400000,
    maxOutputTokens: 128000,
    description: null,
    aliases: ["openai/custom-gpt-5.4-mini-high","openai/custom-gpt-5.4-mini-low","openai/custom-gpt-5.4-mini-medium","openai/custom-gpt-5.4-mini-xhigh"],
    inputModalities: ["image","text"],
    outputModalities: ["text"],
    endpoints: ["chat","responses"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["max_tokens","messages","reasoning","response_format","seed","stop","temperature","tool_choice","tools","top_p","user"]},{"type":"responses","supportsStreaming":true,"supportedParameters":["input","instructions","max_output_tokens","reasoning","temperature","text","tool_choice","tools","top_p","user"]}],
    supportedParameters: ["input","instructions","max_output_tokens","max_tokens","messages","reasoning","response_format","seed","stop","temperature","text","tool_choice","tools","top_p","user"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.1,
    providerOutputUsd: 0.1,
  },
  {
    id: "openai/gpt-5.5",
    name: "GPT 5.5",
    provider: "OpenAI",
    providerSlug: "openai",
    type: "Metin",
    context: "1.05M",
    contextTokens: 1050000,
    maxOutputTokens: 128000,
    description: null,
    aliases: ["openai/cursor55high","openai/cursor55low","openai/cursor55medium","openai/cursor55xhigh","openai/custom-gpt-5.5-high","openai/custom-gpt-5.5-low","openai/custom-gpt-5.5-medium","openai/custom-gpt-5.5-xhigh"],
    inputModalities: ["image","text"],
    outputModalities: ["text"],
    endpoints: ["chat","responses"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["include_reasoning","max_completion_tokens","max_tokens","reasoning","response_format","seed","structured_outputs","tool_choice","tools"]},{"type":"responses","supportsStreaming":true,"supportedParameters":["include_reasoning","max_completion_tokens","max_tokens","reasoning","response_format","seed","structured_outputs","tool_choice","tools"]}],
    supportedParameters: ["include_reasoning","max_completion_tokens","max_tokens","reasoning","response_format","seed","structured_outputs","tool_choice","tools"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.2,
    providerOutputUsd: 0.2,
  },
  {
    id: "openai/gpt-image-2",
    name: "GPT Image 2",
    provider: "OpenAI",
    providerSlug: "openai",
    type: "Görsel",
    context: "272K",
    contextTokens: 272000,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["text"],
    outputModalities: ["image"],
    endpoints: ["chat","images_generations"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","model","prompt","quality","resolution"]},{"type":"images_generations","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","model","prompt","quality","resolution"]}],
    supportedParameters: ["aspect_ratio","enable_base64_output","model","prompt","quality","resolution"],
    pricingUnit: "usd_per_million_tokens",
    providerImageInputUsd: 0.8,
    providerImageOutputUsd: 1.5,
  },
  {
    id: "openai/gpt-image-2-edit",
    name: "GPT Image 2 Edit",
    provider: "OpenAI",
    providerSlug: "openai",
    type: "Görsel",
    context: "—",
    contextTokens: null,
    maxOutputTokens: null,
    description: null,
    inputModalities: ["image","text"],
    outputModalities: ["image"],
    endpoints: ["chat","images_generations","images_edits"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","images","model","prompt","quality","resolution","response_format","size"]},{"type":"images_generations","supportsStreaming":true,"supportedParameters":["aspect_ratio","enable_base64_output","images","model","prompt","quality","resolution","response_format","size"]},{"type":"images_edits","supportsStreaming":false,"supportedParameters":["aspect_ratio","enable_base64_output","images","model","prompt","quality","resolution","response_format","size"]}],
    supportedParameters: ["aspect_ratio","enable_base64_output","images","model","prompt","quality","resolution","response_format","size"],
    pricingUnit: "usd_per_million_tokens",
    providerImageInputUsd: 0.8,
    providerImageOutputUsd: 1.5,
  },
  // Qwen
  {
    id: "qwen/qwen3.6-plus",
    name: "Qwen 3.6 Plus",
    provider: "Qwen",
    providerSlug: "qwen",
    type: "Metin",
    context: "1M",
    contextTokens: 1000000,
    maxOutputTokens: 65536,
    description: null,
    inputModalities: ["text"],
    outputModalities: ["text"],
    endpoints: ["chat"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["include_reasoning","max_tokens","presence_penalty","reasoning","response_format","seed","structured_outputs","temperature","tool_choice","tools","top_p"]}],
    supportedParameters: ["include_reasoning","max_tokens","presence_penalty","reasoning","response_format","seed","structured_outputs","temperature","tool_choice","tools","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.1,
    providerOutputUsd: 0.1,
  },
  // Z.ai
  {
    id: "z-ai/glm-5.1",
    name: "GLM 5.1",
    provider: "Z.ai",
    providerSlug: "z-ai",
    type: "Metin",
    context: "203K",
    contextTokens: 202752,
    maxOutputTokens: 65536,
    description: null,
    inputModalities: ["text"],
    outputModalities: ["text"],
    endpoints: ["chat"],
    endpointDetails: [{"type":"chat","supportsStreaming":true,"supportedParameters":["frequency_penalty","include_reasoning","logit_bias","logprobs","max_tokens","min_p","parallel_tool_calls","presence_penalty","reasoning","reasoning_effort","repetition_penalty","response_format","seed","stop","structured_outputs","temperature","tool_choice","tools","top_k","top_logprobs","top_p"]}],
    supportedParameters: ["frequency_penalty","include_reasoning","logit_bias","logprobs","max_tokens","min_p","parallel_tool_calls","presence_penalty","reasoning","reasoning_effort","repetition_penalty","response_format","seed","stop","structured_outputs","temperature","tool_choice","tools","top_k","top_logprobs","top_p"],
    pricingUnit: "usd_per_million_tokens",
    providerInputUsd: 0.1,
    providerOutputUsd: 0.1,
  },
];
